### INDEX
GET {{server}}/v2/rack?expand=warehouseArea
Authorization: Basic {{username}} {{password}}
Accept: application/json

### VIEW
GET {{server}}/v2/rack/view?id=2
Authorization: Basic {{username}} {{password}}
Accept: application/json

### CREATE
POST {{server}}/v2/rack/create
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "external_id": "1234",
  "code": "code",
  "levels": 1,
  "active": 1,
  "warehouse_area_id": 1
}

### CREATE BAD
POST {{server}}/v2/rack/create
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "external_id": "id 13",
  "description": "test",
  "acronym": "A",
  "code": "A",
  "active": 1,
  "levels": 1,
  "status_id": 12
}



### UPDATE
PUT {{server}}/v2/rack/update?id=2
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "id": 2,
  "external_id": "id 1134123531241241",
  "description": "test",
  "acronym": "B",
  "status_id": 12,
  "warehouse_id": 1
}

### Barcode defined Fields
POST {{server}}/v2/rack/barcode
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "ids": [
    2
  ],
  "barcodeLabelTemplateId": 1,
  "barcodePrintOps": {
    "colOffset": 0,
    "lineEndChar": "\n",
    "printerName": "my printer",
    "printerPower": 10,
    "printerQty": 1,
    "printerSpeed": 4,
    "rowOffset": 0
  }
}