# INDEX
###
GET {{server}}/v2/item?expand=itemCategory
Authorization: Basic {{username}} {{password}}
Accept: application/json

###

# INDEX WITH PRICES
###
GET {{server}}/v2/item?expand=itemPriceListContents
Authorization: Basic {{username}} {{password}}
Accept: application/json

###

# VIEW
###
GET {{server}}/v2/item/view?id=209315&expand=itemPriceListContents
Authorization: Basic {{username}} {{password}}
Accept: application/json


# VIEW
###
GET {{server}}/v2/item/view?id=209493&expand=itemCategory,itemPriceListContents
Authorization: Basic {{username}} {{password}}
Accept: application/json

# CREATE
###
POST {{server}}/v2/item/create
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "external_id": "id 13",
  "description": "test",
  "acronym": "A",
  "status_id": 12,
  "row_creation_date": "2023-07-14 01:37:58",
  "row_modification_date": "2023-07-14 01:37:58"
}

###

# UPDATE
###
PUT {{server}}/v2/item/update?id=2
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "id": 2,
  "external_id": "id 13",
  "description": "testing modify",
  "acronym": "A",
  "status_id": 12,
  "row_creation_date": "2023-07-14 01:37:58",
  "row_modification_date": "2023-07-14 01:37:58"
}

###
# Barcode defined Fields
###
GET {{server}}/v2/item/defined-fields
Authorization: Basic {{username}} {{password}}
Accept: application/json

###

###
# Barcode defined Fields
###
POST {{server}}/v2/item/barcode
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "ids": [
    2,
    209296,
    209297
  ],
  "barcodeLabelTemplateId": 1,
  "barcodePrintOps": {
    "colOffset": 0,
    "lineEndChar": "\n",
    "printerName": "my printer",
    "printerPower": 10,
    "printerQty": 1,
    "printerSpeed": 4,
    "rowOffset": 0
  }
}

###
# Barcode defined Fields
###
POST {{server}}/v2/item/barcode-code
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "code": "test",
  "barcodeLabelTemplateId": 1,
  "barcodePrintOps": {
    "colOffset": 0,
    "lineEndChar": "\n",
    "printerName": "my printer",
    "printerPower": 10,
    "printerQty": 1,
    "printerSpeed": 4,
    "rowOffset": 0
  }
}

###